language: objective-c
osx_image: xcode11.2

#before_install:
#- brew update
#- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

#script:
#- xctool clean build -project MPFormatter.xcodeproj -scheme "MPFormatter iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xctool clean build -project MPFormatter.xcodeproj -scheme "MPFormatter tvOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

#script:
#  - swift build -c debug
#  - swift package generate-xcodeproj

script:
  - xcodebuild -workspace .swiftpm/xcode/package.xcworkspace -scheme MPFormatter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' test
